package com.surgetechnologies.surgeplayer;

import android.os.Bundle;
import android.view.Window;
import android.view.WindowManager;

import androidx.activity.OnBackPressedCallback;
import androidx.core.view.WindowCompat;
import androidx.core.view.WindowInsetsCompat;
import androidx.core.view.WindowInsetsControllerCompat;

import com.google.androidgamesdk.GameActivity;

/*
  Hosts the engine. Window behaviour is driven by bool resources generated by build.gradle
*/

public class SurgeActivity extends GameActivity {

    private boolean mImmersive;
    private boolean mExitOnBack;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        mImmersive = getResources().getBoolean(R.bool.surge_immersive);
        final boolean useCutout = getResources().getBoolean(R.bool.surge_use_cutout);
        final boolean keepScreenOn = getResources().getBoolean(R.bool.surge_keep_screen_on);

        // Must happen before the decor view is created
        final Window window = getWindow();
        final WindowManager.LayoutParams lp = window.getAttributes();
        lp.layoutInDisplayCutoutMode = useCutout
                ? WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES
                : WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_DEFAULT;
        window.setAttributes(lp);

        if (keepScreenOn) {
            window.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
        }

        super.onCreate(savedInstanceState);

        // Draw edge-to-edge; the engine receives the real insets through GameActivity
        WindowCompat.setDecorFitsSystemWindows(window, false);
        applyImmersive();

        // Back button: close the whole app instead of just minimizing it
        mExitOnBack = getResources().getBoolean(R.bool.surge_exit_on_back);
        getOnBackPressedDispatcher().addCallback(this, new OnBackPressedCallback(mExitOnBack) {
            @Override
            public void handleOnBackPressed() {
                finishAndRemoveTask(); // ends the activity and removes it from the recents list
            }
        });
    }

    @Override
    protected void onDestroy() {
        // super.onDestroy() blocks until the native android_main thread has exited
        super.onDestroy();
        // Kill the process on a real exit (not on rotation/recreate) so the next launch is a clean
        if (mExitOnBack && isFinishing()) {
            android.os.Process.killProcess(android.os.Process.myPid());
        }
    }

    @Override
    public void onWindowFocusChanged(boolean hasFocus) {
        super.onWindowFocusChanged(hasFocus);
        // Bars come back after a swipe, a dialog or the keyboard - hide them again when focus returns
        if (hasFocus) {
            applyImmersive();
        }
    }

    private void applyImmersive() {
        if (!mImmersive) {
            return;
        }
        final Window window = getWindow();
        final WindowInsetsControllerCompat controller = WindowCompat.getInsetsController(window, window.getDecorView());
        // Swipe from the edge shows the bars transiently, then they auto-hide
        controller.setSystemBarsBehavior(WindowInsetsControllerCompat.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE);
        controller.hide(WindowInsetsCompat.Type.systemBars());
    }
}